spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 789456
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
        hibernate:
          jdbc:
            lob:
              non_contextual_creation: true
  freemarker:
    expose-request-attributes: true

`